<div class="main_div">
<!--    <div class="" style="float: left;">-->
<!--        <a id="manual-button" class="manual-button" href="#" target="_blank">--><?php //echo __('XPOS'); ?><!--</a>-->
<!---->
<!--    </div>-->
    <div class="btnlable_div">
<!--        <a id="manual-button" class="manual-button" href="javascript:void(0);">--><?php //echo 'Manual Label'; ?><!--</a>-->
        <a id="print-button" class="print-button" href="javascript:void(0);">
            <span class="button-img"><img src=""></span>
            <span style="float: left; padding: 10px;"><?php echo 'Print'; ?></span>
        </a>

    </div>
<!--    <div class="bnt_searchdiv">-->
<!--        <div class="label-wrapper">-->
<!--            <input id="search-input" class="lablesearch input-box" type="text">-->
<!--            <a id="search-button" class="search-button" onclick="searchlablesbysku()" href="javascript:void(0);">--><?php //echo 'Search'; ?><!--</a>-->
<!--        </div>-->
<!--    </div>-->

</div>

<div class="msg_box_popup" id="msg_box_popup" style="display:none; ">
</div>